site_name: PACC HPC Cluster Technical Documentation
site_url: https://mydomain.org/mysite
theme:
  name: material
  logo: /images/pacc1.PNG
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  palette:
    primary: "black"
    accent: "black"
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    #- navigation.tabs
    #- navigation.tabs.sticky
    #- navigation.sections
    - navigation.expand
    - navigation.index
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    #- navigation.footer
    - content.code.copy
    - content.code.select

markdown_extensions:
  - def_list
  - pymdownx.tasklist: 
      custom_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  

plugins:
  - search
  #- table-reader
  - tags

nav:
  - Welcome: index.md
  - Getting Started:
      - Accounts: started/started.md
      - Allocation Details: started/allocation.md
  - Cluster Access: 
      - Access Overview: cluster/access.md 
      - Job Submittion: cluster/jobs.md   
  - Cluster Overview:
    - Hardware Summary: hardware.md
    - Storage: cluster/storage.md
    - Software: cluster/software.md

copyright: UT Health San Antonio  Web Privacy | Links from websites affiliated with UT Health's website (uthscsa.edu) to other websites do not constitute or imply university endorsement of those sites, their content, or products and services associated with those sites. The content on this website is intended to be used for informational purposes only. 

extra:
  generator: false