site_name: UT Health San Antonio PACC HPC Cluster Techinical Docs
site_url: https://mydomain.org/mysite
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    #- navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.index
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share

plugins:
  - search
  - tags
nav:
  - Home: index.md
  - Getting Started:
    - Account: started/started.md
    - Allocation: started/allocation.md
  - Hardware Details: hardware.md
  